"""Placeholder analysis step.

In Phase 2 this will use AI to extract behavioral patterns from conversation
history. For now it produces a stub prompt addition with real statistics to
prove the pipeline works end-to-end.
"""

from __future__ import annotations

from datetime import datetime, timezone

from vardoger.history.models import Conversation


def analyze(conversations: list[Conversation]) -> str:
    """Analyze conversations and return a system prompt addition.

    Currently a placeholder that reports statistics. The actual AI-powered
    analysis will be implemented in Phase 2.
    """
    total_messages = sum(c.message_count for c in conversations)
    user_messages = sum(c.user_message_count for c in conversations)
    assistant_messages = sum(c.assistant_message_count for c in conversations)

    projects = {c.project for c in conversations if c.project}

    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    lines = [
        "# vardoger personalization",
        "",
        f"Generated by vardoger v0.1.0 on {now}.",
        "",
        "This is a placeholder. In a future version, this section will contain",
        "personalized instructions derived from your conversation history.",
        "",
        "## Statistics",
        "",
        f"- Conversations analyzed: {len(conversations)}",
        f"- Total messages: {total_messages}",
        f"  - User messages: {user_messages}",
        f"  - Assistant messages: {assistant_messages}",
    ]

    if projects:
        lines.append(f"- Projects seen: {len(projects)}")

    return "\n".join(lines) + "\n"
