# Copyright 2026 David Strupl
# SPDX-License-Identifier: Apache-2.0
"""Write Vardoger personalization to Devin's documented rule surfaces."""

from __future__ import annotations

import logging
import re
from pathlib import Path

from vardoger.writers._projects import ensure_project

logger = logging.getLogger(__name__)

START_MARKER = "<!-- vardoger:start -->"
END_MARKER = "<!-- vardoger:end -->"

_SECTION_RE = re.compile(
    re.escape(START_MARKER) + r".*?" + re.escape(END_MARKER),
    re.DOTALL,
)

_PROJECT_FRONTMATTER = """---
description: Personal working preferences generated by Vardoger
trigger: always_on
---

"""


def write_devin_rules(
    content: str,
    scope: str = "global",
    project_path: Path | None = None,
) -> Path:
    """Write global AGENTS.md rules or a dedicated project rule file."""
    output_path = _rules_path(scope, project_path)
    if scope == "project":
        ensure_project(project_path or Path.cwd(), platform="Devin")
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(_PROJECT_FRONTMATTER + content, encoding="utf-8")
    else:
        output_path.parent.mkdir(parents=True, exist_ok=True)
        section = _wrap(content)
        if output_path.is_file():
            existing = output_path.read_text(encoding="utf-8")
            if _SECTION_RE.search(existing):
                updated = _SECTION_RE.sub(section, existing)
            else:
                updated = existing.rstrip() + "\n\n" + section + "\n"
        else:
            updated = section + "\n"
        output_path.write_text(updated, encoding="utf-8")
    logger.info("Wrote Devin rules to %s", output_path)
    return output_path


def read_devin_rules(
    scope: str = "global",
    project_path: Path | None = None,
) -> str | None:
    """Return only Vardoger-managed content from Devin's rule surface."""
    output_path = _rules_path(scope, project_path)
    if not output_path.is_file():
        return None
    existing = output_path.read_text(encoding="utf-8")
    if scope == "project":
        if existing.startswith(_PROJECT_FRONTMATTER):
            return existing[len(_PROJECT_FRONTMATTER) :]
        return existing
    match = _SECTION_RE.search(existing)
    if match is None:
        return None
    section = match.group(0)
    return section[len(START_MARKER) : -len(END_MARKER)].strip("\n")


def clear_devin_rules(
    scope: str = "global",
    project_path: Path | None = None,
) -> bool:
    """Remove Vardoger's project file or fenced global AGENTS.md section."""
    output_path = _rules_path(scope, project_path)
    if not output_path.is_file():
        return False
    if scope == "project":
        output_path.unlink()
        return True
    existing = output_path.read_text(encoding="utf-8")
    if not _SECTION_RE.search(existing):
        return False
    updated = _SECTION_RE.sub("", existing).strip()
    if updated:
        output_path.write_text(updated + "\n", encoding="utf-8")
    else:
        output_path.unlink()
    return True


def _rules_path(scope: str, project_path: Path | None) -> Path:
    if scope == "project":
        return (project_path or Path.cwd()) / ".devin" / "rules" / "vardoger.md"
    return Path.home() / ".config" / "devin" / "AGENTS.md"


def _wrap(content: str) -> str:
    return f"{START_MARKER}\n{content}\n{END_MARKER}"
