# Copyright 2026 David Strupl
# SPDX-License-Identifier: Apache-2.0
"""Write vardoger output as an OpenClaw skill.

OpenClaw reads skills from:
  ~/.openclaw/skills/<name>/SKILL.md   (global / user-level)
  <project>/skills/<name>/SKILL.md     (project-level)

vardoger owns the vardoger-personalization skill directory entirely and
overwrites SKILL.md on each run.
"""

from __future__ import annotations

import logging
from pathlib import Path

logger = logging.getLogger(__name__)

SKILL_DIR_NAME = "vardoger-personalization"

SKILL_HEADER = """\
# Personalized instructions generated by vardoger

These instructions were extracted from your conversation history by vardoger.
They describe your preferences, communication style, technical stack, and
workflow so the assistant can better match how you work.

"""


def write_openclaw_rules(
    content: str,
    scope: str = "global",
    project_path: Path | None = None,
) -> Path:
    """Write the vardoger personalization as an OpenClaw SKILL.md file.

    scope="global": writes to ~/.openclaw/skills/vardoger-personalization/SKILL.md
    scope="project": writes to <project>/skills/vardoger-personalization/SKILL.md

    Returns the path of the written file.
    """
    if scope == "project":
        base = project_path or Path.cwd()
        skill_dir = base / "skills" / SKILL_DIR_NAME
    else:
        skill_dir = Path.home() / ".openclaw" / "skills" / SKILL_DIR_NAME

    skill_dir.mkdir(parents=True, exist_ok=True)
    output_path = skill_dir / "SKILL.md"
    output_path.write_text(SKILL_HEADER + content, encoding="utf-8")

    logger.info("Wrote OpenClaw skill to %s", output_path)
    return output_path
