# Copyright 2026 David Strupl
# SPDX-License-Identifier: Apache-2.0
"""Tests for the Cursor prompt writer."""

import tempfile
from pathlib import Path

import pytest

from vardoger.writers.cursor import (
    FRONTMATTER,
    NotAProjectError,
    _find_project_root,
    clear_cursor_rules,
    read_cursor_rules,
    write_cursor_rules,
)


def _as_project(dir_: Path) -> Path:
    """Create ``dir_`` (if needed) and attach a ``.git`` marker so the writer accepts it."""
    dir_.mkdir(parents=True, exist_ok=True)
    (dir_ / ".git").mkdir(exist_ok=True)
    return dir_


def test_creates_mdc_file_with_valid_frontmatter():
    with tempfile.TemporaryDirectory() as tmp:
        project = _as_project(Path(tmp))
        path = write_cursor_rules("test content", project_path=project)

        assert path.exists()
        assert path == project / ".cursor" / "rules" / "vardoger.mdc"
        assert path.read_text(encoding="utf-8") == FRONTMATTER + "\ntest content"
        assert FRONTMATTER == (
            "---\n"
            "description: Personalized instructions generated by vardoger\n"
            "alwaysApply: true\n"
            "---\n"
        )


def test_round_trip_write_then_read():
    with tempfile.TemporaryDirectory() as tmp:
        project = _as_project(Path(tmp))
        body = "# Body\n- rule A\n- rule B\n"
        write_cursor_rules(body, project_path=project)
        assert read_cursor_rules(project_path=project) == body


def test_read_returns_none_when_absent():
    with tempfile.TemporaryDirectory() as tmp:
        assert read_cursor_rules(project_path=Path(tmp)) is None


def test_read_falls_back_to_legacy_md_without_modifying_it(tmp_path: Path) -> None:
    project = _as_project(tmp_path / "project")
    legacy = project / ".cursor" / "rules" / "vardoger.md"
    legacy.parent.mkdir(parents=True)
    legacy.write_text(FRONTMATTER + "\nlegacy body\n", encoding="utf-8")

    assert read_cursor_rules(project_path=project) == "legacy body\n"
    assert legacy.read_text(encoding="utf-8") == FRONTMATTER + "\nlegacy body\n"


def test_write_creates_mdc_and_preserves_legacy_md(tmp_path: Path) -> None:
    project = _as_project(tmp_path / "project")
    legacy = project / ".cursor" / "rules" / "vardoger.md"
    legacy.parent.mkdir(parents=True)
    legacy.write_text("legacy content\n", encoding="utf-8")

    output = write_cursor_rules("current content\n", project_path=project)

    assert output.name == "vardoger.mdc"
    assert read_cursor_rules(project_path=project) == "current content\n"
    assert legacy.read_text(encoding="utf-8") == "legacy content\n"


def test_clear_removes_file():
    with tempfile.TemporaryDirectory() as tmp:
        project = _as_project(Path(tmp))
        write_cursor_rules("x", project_path=project)
        assert clear_cursor_rules(project_path=project) is True
        assert read_cursor_rules(project_path=project) is None
        # Second clear is a no-op.
        assert clear_cursor_rules(project_path=project) is False


def test_clear_preserves_legacy_md(tmp_path: Path) -> None:
    project = _as_project(tmp_path / "project")
    legacy = project / ".cursor" / "rules" / "vardoger.md"
    legacy.parent.mkdir(parents=True)
    legacy.write_text("legacy content\n", encoding="utf-8")

    write_cursor_rules("current content", project_path=project)

    assert clear_cursor_rules(project_path=project) is True
    assert legacy.read_text(encoding="utf-8") == "legacy content\n"
    assert read_cursor_rules(project_path=project) == "legacy content\n"


# ---------------------------------------------------------------------------
# Project-marker validation — regression for
# https://github.com/dstrupl/vardoger/issues/18
# ---------------------------------------------------------------------------


def test_write_refuses_non_project_dir(tmp_path: Path) -> None:
    """A path with no project markers must be rejected, not silently written."""
    bare = tmp_path / "nothome"
    bare.mkdir()
    with pytest.raises(NotAProjectError):
        write_cursor_rules("content", project_path=bare)


def test_write_accepts_nested_subdir_of_project(tmp_path: Path) -> None:
    """Writing inside a project subdirectory is fine — the marker lives in an ancestor."""
    project = _as_project(tmp_path / "proj")
    nested = project / "packages" / "service"
    nested.mkdir(parents=True)
    output = write_cursor_rules("body", project_path=nested)
    assert output.is_file()
    assert (nested / ".cursor" / "rules" / "vardoger.mdc").is_file()


def test_find_project_root_detects_each_marker(tmp_path: Path) -> None:
    """Each marker in PROJECT_MARKERS should independently anchor a project root."""
    for marker in ("pyproject.toml", "package.json", "AGENTS.md", ".cursor"):
        sub = tmp_path / f"proj-{marker.lstrip('.').replace('.', '-')}"
        sub.mkdir()
        if marker.endswith((".toml", ".json", ".md")):
            (sub / marker).write_text("")
        else:
            (sub / marker).mkdir()
        assert _find_project_root(sub) == sub.resolve()
