# Copyright 2026 David Strupl
# SPDX-License-Identifier: Apache-2.0
"""Tests for the OpenClaw prompt writer."""

import tempfile
from pathlib import Path

import pytest

from vardoger.writers._projects import NotAProjectError, find_project_root
from vardoger.writers.openclaw import (
    clear_openclaw_rules,
    read_openclaw_rules,
    write_openclaw_rules,
)


def _as_project(dir_: Path) -> Path:
    """Create ``dir_`` (if needed) and attach a ``.git`` marker."""
    dir_.mkdir(parents=True, exist_ok=True)
    (dir_ / ".git").mkdir(exist_ok=True)
    return dir_


def test_creates_skill_md_project_scope():
    with tempfile.TemporaryDirectory() as tmp:
        project = _as_project(Path(tmp) / "myproject")

        path = write_openclaw_rules(
            "Be concise.",
            scope="project",
            project_path=project,
        )

        expected = project / "skills" / "vardoger-personalization" / "SKILL.md"
        assert path == expected
        assert path.exists()
        text = path.read_text()
        assert "Be concise." in text
        assert "# Personalized instructions generated by vardoger" in text


def test_project_scope():
    with tempfile.TemporaryDirectory() as tmp:
        project = _as_project(Path(tmp) / "myproject")

        path = write_openclaw_rules(
            "Use Python.",
            scope="project",
            project_path=project,
        )

        expected = project / "skills" / "vardoger-personalization" / "SKILL.md"
        assert path == expected
        assert path.exists()
        assert "Use Python." in path.read_text()


def test_idempotent_overwrite():
    with tempfile.TemporaryDirectory() as tmp:
        project = _as_project(Path(tmp) / "proj")

        write_openclaw_rules("first pass", scope="project", project_path=project)
        write_openclaw_rules("second pass", scope="project", project_path=project)

        text = (project / "skills" / "vardoger-personalization" / "SKILL.md").read_text()
        assert "second pass" in text
        assert "first pass" not in text


def test_round_trip_strips_header():
    with tempfile.TemporaryDirectory() as tmp:
        project = _as_project(Path(tmp) / "proj")
        body = "Some body content.\n"
        write_openclaw_rules(body, scope="project", project_path=project)
        assert read_openclaw_rules(scope="project", project_path=project) == body


def test_read_returns_none_when_absent():
    with tempfile.TemporaryDirectory() as tmp:
        assert read_openclaw_rules(scope="project", project_path=Path(tmp) / "no") is None


def test_clear_removes_file():
    with tempfile.TemporaryDirectory() as tmp:
        project = _as_project(Path(tmp) / "proj")
        write_openclaw_rules("x", scope="project", project_path=project)
        assert clear_openclaw_rules(scope="project", project_path=project) is True
        assert read_openclaw_rules(scope="project", project_path=project) is None
        assert clear_openclaw_rules(scope="project", project_path=project) is False


# ---------------------------------------------------------------------------
# Project-marker validation — regression for
# https://github.com/dstrupl/vardoger/issues/21
# ---------------------------------------------------------------------------


def test_project_scope_refuses_non_project_dir(tmp_path: Path) -> None:
    """scope=project must reject a directory with no project markers."""
    bare = tmp_path / "nothome"
    bare.mkdir()
    with pytest.raises(NotAProjectError):
        write_openclaw_rules("content", scope="project", project_path=bare)


def test_project_scope_accepts_nested_subdir_of_project(tmp_path: Path) -> None:
    """Writing inside a project subdirectory is fine."""
    project = _as_project(tmp_path / "proj")
    nested = project / "packages" / "service"
    nested.mkdir(parents=True)
    output = write_openclaw_rules("body", scope="project", project_path=nested)
    assert output.is_file()
    assert output == nested / "skills" / "vardoger-personalization" / "SKILL.md"


def test_global_scope_does_not_validate_project(tmp_path: Path) -> None:
    """scope=global writes under ~/.openclaw/ without touching project validation."""
    bare_home = tmp_path / "bare_home"
    bare_home.mkdir()
    from unittest.mock import patch

    with patch("vardoger.writers.openclaw.Path.home", return_value=bare_home):
        path = write_openclaw_rules("body", scope="global")
    assert path == bare_home / ".openclaw" / "skills" / "vardoger-personalization" / "SKILL.md"


def test_find_project_root_detects_pyproject(tmp_path: Path) -> None:
    """pyproject.toml anchors a project root."""
    project = tmp_path / "proj"
    project.mkdir()
    (project / "pyproject.toml").write_text("")
    nested = project / "a" / "b"
    nested.mkdir(parents=True)
    assert find_project_root(nested) == project.resolve()
