# Copyright 2026 David Strupl
# SPDX-License-Identifier: Apache-2.0
"""Tests for the OpenClaw prompt writer."""

import tempfile
from pathlib import Path

from vardoger.writers.openclaw import write_openclaw_rules


def test_creates_skill_md_project_scope():
    with tempfile.TemporaryDirectory() as tmp:
        project = Path(tmp) / "myproject"
        project.mkdir()

        path = write_openclaw_rules(
            "Be concise.",
            scope="project",
            project_path=project,
        )

        expected = project / "skills" / "vardoger-personalization" / "SKILL.md"
        assert path == expected
        assert path.exists()
        text = path.read_text()
        assert "Be concise." in text
        assert "# Personalized instructions generated by vardoger" in text


def test_project_scope():
    with tempfile.TemporaryDirectory() as tmp:
        project = Path(tmp) / "myproject"
        project.mkdir()

        path = write_openclaw_rules(
            "Use Python.",
            scope="project",
            project_path=project,
        )

        expected = project / "skills" / "vardoger-personalization" / "SKILL.md"
        assert path == expected
        assert path.exists()
        assert "Use Python." in path.read_text()


def test_idempotent_overwrite():
    with tempfile.TemporaryDirectory() as tmp:
        project = Path(tmp) / "proj"
        project.mkdir()

        write_openclaw_rules("first pass", scope="project", project_path=project)
        write_openclaw_rules("second pass", scope="project", project_path=project)

        text = (project / "skills" / "vardoger-personalization" / "SKILL.md").read_text()
        assert "second pass" in text
        assert "first pass" not in text
